### ISSUE TITLE
[Bug] use univer api to export excel run 403 error 

### ISSUE THREAD

**Issue by mukiwu** [dream-num/univer#2813]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.3

### Reproduction link

we use docker compose for unver api, but when I export excel (另存), it show 403 error.
here is the demo url: [https://excel.goodlinker.io:3010/](https://excel.goodlinker.io:3010/)
.
the docker gave use http url, but our project have to use https, so here is our setting:

```
S3_ENDPOINT_PUBLIC=https://excel.goodlinker.io:19000
```

### docker-compose.yaml

`docker-compose.yaml`:  we comment `${HOST_MINIO_PORT}:9000`

```
univer-minio:
    restart: always
    image: bitnami/minio:${MINIO_VERSION}
    container_name: univer-minio
    environment:
      - MINIO_ROOT_USER=${S3_USER}
      - MINIO_ROOT_PASSWORD=${S3_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=${S3_DEFAULT_BUCKET}
      - MINIO_DATA_DIR=/data
        #ports:
        #- ${HOST_MINIO_PORT}:9000
    expose:
      - 9000
    networks:
      - univer
    labels:
      - com.univer.app=minio
    volumes:
      - minio-data:/data
```

### universer.conf

`universer.conf`: we add setting about port 3010 & 19000

```
upstream universer {

    least_conn;

    server universer:8000;

}
 
map $http_upgrade $connection_upgrade {

    default upgrade;

    '' close;

}
 
# Redirect HTTP to HTTPS

server {

    listen 80;

    server_name excel.goodlinker.io;

    return 301 https://$host$request_uri;

}
 
# HTTPS server block

server {

    listen 443 ssl;

    server_name excel.goodlinker.io;
 
    ssl_certificate /etc/nginx/certs/fullchain.pem;

    ssl_certificate_key /etc/nginx/certs/privkey.pem;
 
    ssl_protocols TLSv1.2 TLSv1.3;

    ssl_prefer_server_ciphers on;

    ssl_ciphers HIGH:!aNULL:!MD5;
 
    client_max_body_size 100m;
 
    location / {

        proxy_pass http://universer;

    }
 
    location /universer-api/comb/connect {

        proxy_pass http://universer;

        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;

        proxy_set_header Connection $connection_upgrade;

    }
 
    location /universer-api/metrics {

        return 403;

    }

}
 
server {

    listen 8000;
 
    # resolver 127.0.0.11 valid=10s;

    # resolver_timeout 5s;
 
    client_max_body_size 100m;
 
    location / {

        proxy_pass http://universer;

    }
 
    location /universer-api/comb/connect {

        proxy_pass http://universer;

        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;

        proxy_set_header Connection $connection_upgrade;

    }
 
    location /universer-api/metrics {

        return 403;

    }

}
 
# HTTPS server block for port 3010

server {

    listen 3010 ssl;

    server_name excel.goodlinker.io;
 
    ssl_certificate /etc/nginx/certs/fullchain.pem;

    ssl_certificate_key /etc/nginx/certs/privkey.pem;
 
    ssl_protocols TLSv1.2 TLSv1.3;

    ssl_prefer_server_ciphers on;

    ssl_ciphers HIGH:!aNULL:!MD5;
 
    client_max_body_size 100m;
 
    location / {

        proxy_pass http://univer-collaboration-lite:3010;

	proxy_set_header Host $host;

        proxy_set_header X-Real-IP $remote_addr;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_set_header X-Forwarded-Proto $scheme;

    }
 
    location /universer-api/comb/connect {

        proxy_pass http://univer-collaboration-lite:3010;

        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;

        proxy_set_header Connection $connection_upgrade;

    }

}
 
# HTTPS server block for port 19000

server {

    listen 19000 ssl;

    server_name excel.goodlinker.io;
 
    ssl_certificate /etc/nginx/certs/fullchain.pem;

    ssl_certificate_key /etc/nginx/certs/privkey.pem;
 
    ssl_protocols TLSv1.2 TLSv1.3;

    ssl_prefer_server_ciphers on;

    ssl_ciphers HIGH:!aNULL:!MD5;
 
    client_max_body_size 100m;
 
    location / {

        proxy_pass http://univer-minio:9000;

        proxy_set_header Host $host;

        proxy_set_header X-Real-IP $remote_addr;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_set_header X-Forwarded-Proto $scheme;

    }
 
 
}
```
 
and no error log in docker log.

will docker offer https url, or can solve 403 issue ? thanks

### Expected behavior

can export excel

### Actual behavior

403 Forbidden
